language: c

arch: 
    - amd64
    - arm64

cache:
  directories:
    - '$HOME/.sonar/cache'

addons:
    sonarcloud:
        organization: "openscap"
    apt:
       packages:
           - lcov
           - libdbus-1-dev
           - libdbus-glib-1-dev
           - libcurl4-openssl-dev
           - libgcrypt-dev
           - libselinux1-dev
           - libgconf2-dev
           - libacl1-dev
           - libblkid-dev
           - libcap-dev
           - libxml2-dev
           - swig
           - libxml-parser-perl
           - libxml-xpath-perl
           - libperl-dev
           - librpm-dev
           - swig
           - librtmp-dev
           - xsltproc
           - rpm-common
           - lua50
matrix:
  include:
    - os: osx
      before_install:
        - brew update
        - brew remove python@2
        - brew install doxygen
        - brew install opendbx
        - brew install popt
        - brew install swig
      before_script:
        - cd build
      script:
        - cmake -DENABLE_PROBES=false ../
        - make -j 4
before_script:
  - cd build
script:
  - cmake -DCMAKE_BUILD_TYPE=Debug ../
  - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then 
      build-wrapper-linux-aarch64 --out-dir bw-output make all || make all;
    fi
  - build-wrapper-linux-aarch64 --out-dir bw-output make all || make all  # build-wrapper won't work on forked repositories.
  - ctest --output-on-failure
  - (cd .. && sonar-scanner) || true  # Will always fail builds on forked repositories.
